

services:
  web:
    image: nginx:latest
    ports:
      - "81:81"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fatoutfatout1
      MYSQL_DATABASE: springdb1
    ports:
      - "3307:3306"

