

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fatoutfatout1
      MYSQL_DATABASE: springdb1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    image: myapp:v1.0
    restart: always
    ports:
      - '8081:8081'  # Adjust port as per your Spring Boot application configuration
    depends_on:
      - db

