version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fatoutfatout1
      MYSQL_DATABASE: springdb1
      MYSQL_USER: root
      MYSQL_PASSWORD: fatoutfatout1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
